version: "3.9"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: foliox-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: asset-postgres      # use container name — both now on same network
      DB_PORT: 5432
    ports:
      - "5000:5000"
    networks:
      - foliox-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: foliox-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - foliox-net

networks:
  foliox-net:
    driver: bridge